### ISSUE TITLE
Object Discriminant Issue

### ISSUE THREAD

**Issue by davidgarland** [nim-lang/irc#11]
On [line 449](https://github.com/nim-lang/irc/blob/4ba43e6003106ccf237e1e2cecc137a5f4a989b9/src/irc.nim#L449) an object discriminant is set, which leads to a runtime crash now.

**Comment by davidgarland** [comment]
This also appears to happen on line 471 and line 501; not sure if those are actually an issue, though.

**Comment by dom96** [comment]
Yeah, these are bugs (Nim used to allow this).

Fix is to simply do something like: ``ev = IrcEvent(typ: EvTimeout)``. Up for a PR? :)

**Comment by davidgarland** [comment]
Sounds good, I'll take a stab at it.

**Comment by davidgarland** [comment]
Finished, and attempted a fix at another thing while I was at it.

**Comment by davidgarland** [comment]
I may actually have to do another PR for this, as this seems to also happen on line 366 occasionally.

**Comment by davidgarland** [comment]
Done. https://github.com/nim-lang/irc/pull/15
